### ISSUE TITLE
Inverse of singular matrix doesn't exist, so what does the solution represent ??

### ISSUE THREAD

**Issue by lavish619** [KingJamesSong/FastDifferentiableMatSqrt#1]
Hi,

I was using the code for the inversion of a covariance matrix, but the covariance matrix I have created is from a single data point i.e A@A.T where A is a vector of shape (n,1). 

So A@A.T is a rank1 matrix of shape (n,n). So the inverse should not exist for this matrix.
But, when calculating the inverse of this matrix, the method provides a solution. 

So I wanted to ask what is this solution. Since the method is iterative, so it approximates the result, but to what result is it approximating 
 ??

**Comment by KingJamesSong** [comment]
Thanks for your interest in our work!

Yes, in the case of a singular matrix, the exact inverse should not exist and at least (n-1) eigenvalues should be **INF**.

But as you pointed out, our method is iterative and approximate. **The eigenvalues of inverse should be very large but not infinite**. You can check this by printing the eigenvalues of the inverse as:

> u, s, v = torch.linalg.svd(approximate_matrix)
>print(s)

Thanks again and let me know if you have any further questions!

**Comment by lavish619** [comment]
Thanks a lot for the explanation.
