### ISSUE TITLE
A question of  compute P and Q weithou P = I - P, Q = I - Q

### ISSUE THREAD

**Issue by HongLouyemeng** [KingJamesSong/FastDifferentiableMatSqrt#2]
(https://github.com/KingJamesSong/FastDifferentiableMatSqrt/blob/466c9bf5f7ca5c3a405e104197e63f20b1c70114/torch_utils.py#L28-L40)

why not
 $p \underline{} sqrt = \mathbf{I}  - p \underline{} sqrt,q \underline{} sqrt=\mathbf{I} - q \underline{} sqrt $
This seems inconsistent with the formula in the paper

**Comment by KingJamesSong** [comment]
Hi,

  Thanks for your interest in our work!

  This is because we initialize P and Q with: p_sqrt = pade_p[0]*I, q_sqrt = pade_q[0]*I (here pade_p[0] and pade_q[0] are both 1), and the pade' coefficients pade_p[i>0] and pade_q[i>0] are negative in the code (but assumed positive in the paper by default). 

  Your idea is correct if we rewrite the code as follows:

```python
   def matrix_pade_approximant(p,I):
    p_sqrt = 0.
    q_sqrt = 0.
    p_app = I - p
    p_hat = p_app
    for i in range(5):
        p_sqrt += pade_p[i+1]*p_hat
        q_sqrt += pade_q[i+1]*p_hat
        p_hat = p_hat.bmm(p_app)  
   p_sqrt = I + p_sqrt
   q_sqrt = I + q_sqrt
   return torch.linalg.solve(q_sqrt, p_sqrt)
```

  Let me know if you have further concerns!
  
Kind regards,

Yue Song

**Comment by HongLouyemeng** [comment]
> Hi,
> 
> Thanks for your interest in our work!
> 
> This is because we initialize P and Q with: p_sqrt = pade_p[0]*I, q_sqrt = pade_q[0]*I (here pade_p[0] and pade_q[0] are both 1), and the pade' coefficients pade_p[i>0] and pade_q[i>0] are negative in the code (but assumed positive in the paper by default).
> 
> Your idea is correct if we rewrite the code as follows:
> 
> ```python
>    def matrix_pade_approximant(p,I):
>     p_sqrt = 0.
>     q_sqrt = 0.
>     p_app = I - p
>     p_hat = p_app
>     for i in range(5):
>         p_sqrt += pade_p[i+1]*p_hat
>         q_sqrt += pade_q[i+1]*p_hat
>         p_hat = p_hat.bmm(p_app)  
>    p_sqrt = I + p_sqrt
>    q_sqrt = I + q_sqrt
>    return torch.linalg.solve(q_sqrt, p_sqrt)
> ```
> 
> Let me know if you have further concerns!
> 
> Kind regards,
> 
> Yue Song

Thank you for your reply.

**Comment by HongLouyemeng** [comment]
Hi,
the input matrix must be **square matrix**? Because of  $I$ is Identity matrix.

**Comment by KingJamesSong** [comment]
Yes, the matrix should be square and symmetric; otherwise there would be no principal square root.

**Comment by HongLouyemeng** [comment]
> Yes, the matrix should be square and symmetric; otherwise there would be no principal square root.

Thanks for your reply.
