### ISSUE TITLE
The results of matsqrt are not very accurate

### ISSUE THREAD

**Issue by HongLouyemeng** [KingJamesSong/FastDifferentiableMatSqrt#3]
**Hi, KingJamesSong.**  When I use the pade approximation, the **matSqrt** result is wrong, but when I use the Taylor approximation the result is closer to the scipy sqrtm....

**Comment by KingJamesSong** [comment]
Hi,

  Thanks for your interest in our work!

  Could you please give more detailed results and descriptions of your setting and input data?

  Unless the matrix is (close) singular, the pade approximation should always have better results than the Taylor counterpart.

**Comment by HongLouyemeng** [comment]
> Hi,
> 
> Thanks for your interest in our work!
> 
> Could you please give more detailed results and descriptions of your setting and input data?
> 
> Unless the matrix is (close) singular, the pade approximation should always have better results than the Taylor counterpart.

```python
import numpy
from mpmath import *
import numpy as np
import torch
from  scipy.linalg import  sqrtm
mp.dps = 32
one = mpf(1)
mp.pretty = True

def f(x):
    return sqrt(one-x)

# Derive the taylor and pade' coefficients for MTP, MPA
a = taylor(f, 0, 10)
pade_p, pade_q = pade(a, 5, 5)
a = torch.from_numpy(np.array(a).astype(float))
pade_p = torch.from_numpy(np.array(pade_p).astype(float))
pade_q = torch.from_numpy(np.array(pade_q).astype(float))

def matrix_taylor_polynomial(p, I):
    p_sqrt= I
    p_app = I - p
    p_hat = p_app
    for i in range(10):
      p_sqrt += a[i+1]*p_hat
      p_hat = p_hat.bmm(p_app)
    return p_sqrt

def matrix_pade_approximant(p,I):
    p_sqrt = pade_p[0]*I
    q_sqrt = pade_q[0]*I
    p_app = I - p
    p_hat = p_app
    for i in range(5):
        p_sqrt += pade_p[i+1]*p_hat
        q_sqrt += pade_q[i+1]*p_hat
        p_hat = p_hat.bmm(p_app)
    #There are 4 options to compute the MPA: comput Matrix Inverse or Matrix Linear System on CPU/GPU;
    #It seems that single matrix is faster on CPU and batched matrices are faster on GPU
    #Please check which one is faster before running the code;
    return torch.linalg.solve(q_sqrt, p_sqrt)
    #return torch.linalg.solve(q_sqrt.cpu(), p_sqrt.cpu()).cuda()
    #return torch.linalg.inv(q_sqrt).mm(p_sqrt)
    #return torch.linalg.inv(q_sqrt.cpu()).cuda().bmm(p_sqrt)

def matrix_pade_approximant_inverse(p,I):
    p_sqrt = pade_p[0]*I
    q_sqrt = pade_q[0]*I
    p_app = I - p
    p_hat = p_app
    for i in range(5):
        p_sqrt += pade_p[i+1]*p_hat
        q_sqrt += pade_q[i+1]*p_hat
        p_hat = p_hat.bmm(p_app)
    #There are 4 options to compute the MPA_inverse: comput Matrix Inverse or Matrix Linear System on CPU/GPU;
    #It seems that single matrix is faster on CPU and batched matrices are faster on GPU
    #Please check which one is faster before running the code;
    return torch.linalg.solve(p_sqrt, q_sqrt)
    #return torch.linalg.solve(p_sqrt.cpu(), q_sqrt.cpu()).cuda()
    #return torch.linalg.inv(p_sqrt).mm(q_sqrt)
    #return torch.linalg.inv(p_sqrt.cpu()).cuda().bmm(q_sqrt)

#Differentiable Matrix Square Root by MPA_Lya
class MPA_Lya(torch.autograd.Function):
    @staticmethod
    def forward(ctx, M):
        normM = torch.norm(M,dim=[1,2]).reshape(M.size(0),1,1)
        I = torch.eye(M.size(1), requires_grad=False, device=M.device).reshape(1,M.size(1),M.size(1)).repeat(M.size(0),1,1)
        #This is for MTP calculation
        M_sqrt = matrix_taylor_polynomial(M/normM,I)
        # M_sqrt = matrix_pade_approximant(M / normM, I)
        M_sqrt = M_sqrt * torch.sqrt(normM)
        ctx.save_for_backward(M, M_sqrt, normM,  I)
        return M_sqrt

    @staticmethod
    def backward(ctx, grad_output):
        M, M_sqrt, normM,  I = ctx.saved_tensors
        b = M_sqrt / torch.sqrt(normM)
        c = grad_output / torch.sqrt(normM)
        for i in range(8):
            #In case you might terminate the iteration by checking convergence
            #if th.norm(b-I)<1e-4:
            #    break
            b_2 = b.bmm(b)
            c = 0.5 * (c.bmm(3.0*I-b_2)-b_2.bmm(c)+b.bmm(c).bmm(b))
            b = 0.5 * b.bmm(3.0 * I - b_2)
        grad_input = 0.5 * c
        return grad_input

FastMatSqrt = MPA_Lya.apply
rand_matrix = torch.tensor([[1,2],[3,4]]).unsqueeze(0)
rand_cov_sqrt = FastMatSqrt(rand_matrix)
r = sqrtm(rand_matrix.numpy()[0])
r1 = rand_cov_sqrt.numpy()
print(np.dot(r,r))
print(np.dot(r1,r1))
```

**Comment by HongLouyemeng** [comment]
> Hi,
> 
> Thanks for your interest in our work!
> 
> Could you please give more detailed results and descriptions of your setting and input data?
> 
> Unless the matrix is (close) singular, the pade approximation should always have better results than the Taylor counterpart.

This is my current test code that follows scipy's sqrtm.https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.sqrtm.html

**Comment by KingJamesSong** [comment]
Hi,

 The matrix square root is principal (unique) only when the input matrix is **symmetric positive definite**.

 That means, in your case, you should first compute the covariance and then compute the square root:
 ```python
 rand_cov = rand_matrix.bmm(rand_matrix.transpose(1,2))
 rand_cov_sqrt = FastMatSqrt(rand_cov)
 ```
Let me know if you have further questions!

**Comment by HongLouyemeng** [comment]
> Hi,
> 
> The matrix square root is principal (unique) only when the input matrix is **symmetric positive definite**.
> 
> That means, in your case, you should first compute the covariance and then compute the square root:
> 
> ```python
> rand_cov = rand_matrix.bmm(rand_matrix.transpose(1,2))
> rand_cov_sqrt = FastMatSqrt(rand_cov)
> ```
> 
> Let me know if you have further questions!

Hi,
```python
rand_matrix = torch.tensor([[1,2],[3,4]]).unsqueeze(0)
FastMatSqrt = MPA_Lya.apply
rand_cov = rand_matrix.bmm(rand_matrix.transpose(1,2))
rand_cov_sqrt = FastMatSqrt(rand_cov)
```
What is the use of rand_cov_sqrt...After testing, it looks like this
[[[[ 5.7116117 10.685205 ]]

  [[10.685205  25.139256 ]]]]
```python
rand_sqrt = FastMatSqrt(rand_matrix)
```
taylor's result:
[[[[1.2864267 1.8689806]]

  [[2.8034706 4.0898967]]]]

**Comment by KingJamesSong** [comment]
Hi,

  I tried to run the code for input [[1,2],[3,4]] and the MPA result is:
 ```python
tensor([[[1.3820, 1.8062],
         [1.8062, 4.6660]]])
 ```
 where the accurate square root is:
 ```python
tensor([[[ 1.2005    1.8865
    1.8865    4.6305]]])
 ```
 The MPA is closer to the accurate results in terms of Frobienius norm.

 Could you please check where the code goes wrong? The results you show look like the covariance instead of the square root.

**Comment by HongLouyemeng** [comment]
> Hi,
> 
> I tried to run the code for input [[1,2],[3,4]] and the MPA result is:
> 
> ```python
> tensor([[[1.3820, 1.8062],
>         [1.8062, 4.6660]]])
> ```
> 
> where the accurate square root is:
> 
> ```python
> tensor([[[ 1.2005    1.8865
>    1.8865    4.6305]]])
> ```
> 
> The MPA is closer to the accurate results in terms of Frobienius norm.
> 
> Could you please check where the code goes wrong? The results you show look like the covariance instead of the square root.
Hi,
Should I use the eigenvalues and cov_sqrt, But this also does not give accurate results?....maybe the right answer is
array([[ 0.75592895,  1.13389342],
       [ 0.37796447,  1.88982237]])

**Comment by HongLouyemeng** [comment]
> Hi,
> 
> I tried to run the code for input [[1,2],[3,4]] and the MPA result is:
> 
> ```python
> tensor([[[1.3820, 1.8062],
>         [1.8062, 4.6660]]])
> ```
> 
> where the accurate square root is:
> 
> ```python
> tensor([[[ 1.2005    1.8865
>    1.8865    4.6305]]])
> ```
> 
> The MPA is closer to the accurate results in terms of Frobienius norm.
> 
> Could you please check where the code goes wrong? The results you show look like the covariance instead of the square root.

I remembered that this algorithm in my state estimator it is accurate.I do not have such a deep knowledge of matrix theory, so I'm sorry to have wasted so much of your time.

**Comment by HongLouyemeng** [comment]
> Hi,
> 
> I tried to run the code for input [[1,2],[3,4]] and the MPA result is:
> 
> ```python
> tensor([[[1.3820, 1.8062],
>         [1.8062, 4.6660]]])
> ```
> 
> where the accurate square root is:
> 
> ```python
> tensor([[[ 1.2005    1.8865
>    1.8865    4.6305]]])
> ```
> 
> The MPA is closer to the accurate results in terms of Frobienius norm.
> 
> Could you please check where the code goes wrong? The results you show look like the covariance instead of the square root.

Hi,
Should I use the following formula?
<img width="190" alt="image" src="https://user-images.githubusercontent.com/48181529/216655877-3589d733-429e-41a7-92e4-938efd1f3157.png">

**Comment by KingJamesSong** [comment]
Hi,

  Yes, the formula is correct. The covariance step is to make the matrix symmetric and positive definite such that there would be only one principal matrix square root.

  No problem! Let me know if you have further questions!

**Comment by HongLouyemeng** [comment]
> Hi,
> 
> Yes, the formula is correct. The covariance step is to make the matrix symmetric and positive definite such that there would be only one principal matrix square root.
> 
> No problem! Let me know if you have further questions!

**Hi,
Thanks for you answer**
